FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto en el que la aplicación escucha
EXPOSE 3002

# Comando para ejecutar la aplicación
CMD ["node", "index.js"]
