name: CI/CD Pipeline for Users

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'users/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
      ECR_REPOSITORY_USERS: users
      SERVICE_NAME_USERS: users-service
      CLUSTER_NAME: your-ecs-cluster-name

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build, tag, and push Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY_USERS }}:latest ./users
          docker tag ${{ env.ECR_REPOSITORY_USERS }}:latest ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_USERS }}:latest
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_USERS }}:latest

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME_USERS }} --force-new-deployment
