name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-liner script
        run: echo "The workflow is running!"
