name: CI/CD Pipeline for Payments

on:
  push:
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY_PAYMENTS }}

      - name: Build, tag, and push Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY_PAYMENTS }}:latest ./payments
          docker tag ${{ env.ECR_REPOSITORY_PAYMENTS }}:latest ${{ env.ECR_REGISTRY_PAYMENTS }}/${{ env.ECR_REPOSITORY_PAYMENTS }}:latest
          docker push ${{ env.ECR_REGISTRY_PAYMENTS }}/${{ env.ECR_REPOSITORY_PAYMENTS }}:latest

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME_PAYMENTS }} --force-new-deployment
